ALWAYSON_DFOSET = no
AUTO_ADD_GLOBAL_DEFINE_BY_NAME = MTK_FACTORY_MODE_IN_GB2312 MTK_HETCOMM_SUPPORT MTK_CAM_VHDR_SUPPORT MTK_FLV_PLAYBACK_SUPPORT MTK_BESSURROUND_SUPPORT MTK_VOICE_INTERFACE_EXTENSION_SUPPORT MTK_LOSSLESS_BT_SUPPORT MTK_DTAG_DUAL_APN_SUPPORT MTK_DEINTERLACE_SUPPORT MTK_BESLOUDNESS_SUPPORT MTK_WIFI_MCC_SUPPORT MTK_EPDG_SUPPORT MTK_SUPPORT_TC1_TUNNING TARGET_USES_LOGD MTK_SPEAKER_MONITOR_SUPPORT MTK_DUAL_INPUT_CHARGER_SUPPORT MTK_JEITA_STANDARD_SUPPORT MTK_AUDIO_ALAC_SUPPORT MTK_VOICE_CONTACT_SEARCH_SUPPORT MTK_M4U_SUPPORT MTK_SLOW_MOTION_VIDEO_SUPPORT MTK_GPT_SCHEME_SUPPORT MTK_CSD_DIALER_SUPPORT MTK_REGIONALPHONE_SUPPORT MTK_AUTO_DETECT_ALSPS MTK_CAM_MAV_SUPPORT MTK_MTKLOGGER_SUPPORT MTK_ENGINEERMODE_APP MTK_WFD_SINK_UIBC_SUPPORT MTK_WFD_SINK_SUPPORT MTK_PASSPOINT_R2_SUPPORT MTK_VOW_SUPPORT MTK_CAM_HDR_SUPPORT MTK_CAM_STEREO_CAMERA_SUPPORT MTK_CAM_VIDEO_FACEBEAUTY_SUPPORT MTK_CAM_FACEBEAUTY_SUPPORT MTK_CAM_VSS_SUPPORT MTK_CAM_ZSD_SUPPORT MTK_CAM_DEPTH_AF_SUPPORT MTK_CAM_NATIVE_PIP_SUPPORT MTK_CAM_NR3D_SUPPORT MTK_CAM_OT_SUPPORT MTK_CAM_SD_SUPPORT MTK_CAM_IMAGE_REFOCUS_SUPPORT MTK_CAM_ASD_SUPPORT MTK_CAM_FD_SUPPORT MTK_CAM_GESTURE_SUPPORT MTK_MLC_NAND_SUPPORT MTK_SIM_RECOVERY MTK_FAN5402_SUPPORT MTK_AUDIO_HD_REC_SUPPORT MTK_PLAYREADY_SUPPORT MTK_AUDIO MTK_CLEARMOTION_SUPPORT MTK_MOTION_TRACK_SUPPORT MTK_LIVE_PHOTO_SUPPORT MTK_CAMERA_OT_SUPPORT MTK_FSCK_TUNE HW_HAVE_TP_THREAD MTK_NEW_COMBO_EMMC_SUPPORT MTK_PERSIST_PARTITION_SUPPORT MTK_DX_HDCP_SUPPORT MTK_COMBO_NAND_SUPPORT MTK_SMARTBOOK_SUPPORT MTK_DFO_RESOLUTION_SUPPORT MTK_HIGH_RESOLUTION_AUDIO_SUPPORT MTK_AUDIO_EXTCODEC_SUPPORT MTK_SUBTITLE_SUPPORT MTK_WIFIWPSP2P_NFC_SUPPORT MTK_SDIOAUTOK_SUPPORT MTK_MSDC1_NOT_SUPPORT_SDR104 MTK_FEMTO_CELL_SUPPORT MTK_CHIPTEST_INT MTK_USER_ROOT_SWITCH MTK_ENABLE_MD5 MTK_LTE_SUPPORT MTK_LTE_DC_SUPPORT MTK_WMV_PLAYBACK_SUPPORT MTK_WMA_PLAYBACK_SUPPORT MTK_MOBILE_MANAGEMENT MTK_PARTITION_TABLE_PLAIN_TEXT MTK_DOLBY_DAP_SUPPORT MTK_BQ24156_SUPPORT CUSTOM_KERNEL_BAROMETER MTK_BQ24158_SUPPORT MTK_TABLET_PLUGIN_BUILD MTK_WIFI_CALLING_RIL_SUPPORT MTK_MULTI_PARTITION_MOUNT_ONLY_SUPPORT MTK_BQ24297_SUPPORT MTK_3GDONGLE_SUPPORT MTK_PM_STATS_SUPPORT MTK_SWIP_WMAPRO MTK_AUDIO_DDPLUS_SUPPORT MTK_SEC_WFD_VIDEO_PATH_SUPPORT MTK_BATLOWV_NO_PANEL_ON_EARLY MTK_CTP_RESET_CONFIG MTK_SIM_HOT_SWAP_COMMON_SLOT MTK_TER_SERVICE MTK_OWNER_SDCARD_ONLY_SUPPORT MTK_DRM_PLAYREADY_SUPPORT MTK_AUDIO_CHANGE_SUPPORT MTK_VIBSPK_SUPPORT IS_VCORE_USE_6333VCORE IS_VRF18_USE_6333VRF18 IS_VM_USE_6333VM MTK_VIDEO_AUTO_FLASH_SUPPORT MTK_AIV_SUPPORT MTK_WFD_HDCP_TX_SUPPORT PURE_AP_USE_EXTERNAL_MODEM MTK_NO_NEED_USB_LED MTK_HDMI_HDCP_SUPPORT MTK_INTERNAL_HDMI_SUPPORT MTK_INTERNAL_MHL_SUPPORT MTK_DMNR_TUNING_AT_MD NAND_OTP_SUPPORT MTK_DVFS_DISABLE_LOW_VOLTAGE_SUPPORT MTK_VOIP_ENHANCEMENT_SUPPORT MTK_HANDSFREE_DMNR_SUPPORT MTK_SWCHR_SUPPORT MTK_MT6333_SUPPORT MTK_MULTISIM_RINGTONE_SUPPORT MTK_DRM_KEY_MNG_SUPPORT MTK_SEC_VIDEO_PATH_SUPPORT MTK_WVDRM_L1_SUPPORT MTK_IN_HOUSE_TEE_SUPPORT MTK_DISABLE_POWER_ON_OFF_VOLTAGE_LIMITATION MTK_CTA_SUPPORT MTK_MATV_SERIAL_IF_SUPPORT MTK_BIP_SCWS MTK_MDM_FUMO MTK_MDM_LAWMO MTK_MDM_SCOMO MTK_UART_USB_SWITCH MTK_FAT_ON_NAND MTK_AUDIO_RAW_SUPPORT MTK_MD_SHUT_DOWN_NT MTK_CACHE_MERGE_SUPPORT MTK_IPV6_TETHER_PD_MODE MTK_UMTS_TDD128_MODE MTK_YMAL_SCATTER_FILE_SUPPORT MTK_RADIOOFF_POWER_OFF_MD MTK_MT8193_HDCP_SUPPORT MTK_LCEEFT_SUPPORT MTK_USES_VR_DYNAMIC_QUALITY_MECHANISM MTK_PLATFORM_OPTIMIZE MTK_HW_ENHANCE MTK_PQ_SUPPORT MTK_AUDIO_ADPCM_SUPPORT HAVE_ADPCMENCODE_FEATURE MTK_2IN1_SPK_SUPPORT MTK_WEB_NOTIFICATION_SUPPORT MTK_GEMINI_4SIM_SUPPORT MTK_GEMINI_3SIM_SUPPORT MTK_VOICE_UNLOCK_SUPPORT MTK_VOICE_UI_SUPPORT MTK_BEAM_PLUS_SUPPORT MTK_IPOH_SUPPORT MTK_BQ27541_SUPPORT MTK_WFD_SUPPORT MTK_IPV6_TETHER_NDP_MODE MTK_TETHERING_EEM_SUPPORT MTK_AAL_SUPPORT MTK_KERNEL_POWER_OFF_CHARGING MTK_NAND_UBIFS_SUPPORT MTK_FLIGHT_MODE_POWER_OFF_MD MTK_ENABLE_MD1 MTK_ENABLE_MD2 MTK_ACMT_DEBUG MTK_BT_PROFILE_AVRCP MTK_MMPROFILE_SUPPORT MTK_GPS_SUPPORT MTK_MULTIBRIDGE_SUPPORT EVDO_DT_SUPPORT MTK_CAMCORDER_PROFILE_MID_MP4 MTK_FM_SUPPORT MTK_USES_HD_VIDEO MTK_TABLET_PLATFORM MTK_AUTO_DETECT_MAGNETOMETER MTK_BT_PROFILE_MANAGER MTK_NCP1851_SUPPORT MTK_FM_RECORDING_SUPPORT MTK_DEDICATEDAPN_SUPPORT MTK_BT_PROFILE_HIDH MTK_BT_PROFILE_TIMES MTK_DT_SUPPORT MTK_BT_FM_OVER_BT_VIA_CONTROLLER MTK_BT_PROFILE_PBAP MTK_NFC_SUPPORT MTK_BT_PROFILE_HFP MTK_BT_PROFILE_AVRCP14 MTK_MASS_STORAGE MTK_BICR_SUPPORT MTK_BT_PROFILE_BIP MTK_BT_PROFILE_BPP MTK_COMBO_QUICK_SLEEP_SUPPORT MTK_MT8193_SUPPORT HAVE_AACENCODE_FEATURE MTK_BT_PROFILE_MAPS MTK_FM_50KHZ_SUPPORT MTK_COMBO_SUPPORT MTK_BT_PROFILE_OPP MTK_2SDCARD_SWAP CUSTOM_KERNEL_GYROSCOPE MTK_BT_PROFILE_MAPC MTK_SHARED_SDCARD MTK_EMMC_DISCARD MTK_BT_PROFILE_TIMEC MTK_MULTI_STORAGE_SUPPORT CUSTOM_KERNEL_ALSPS MTK_ENABLE_VIDEO_EDITOR CUSTOM_KERNEL_ACCELEROMETER MTK_DUAL_MIC_SUPPORT MTK_WAPI_SUPPORT MTK_FD_SUPPORT MTK_DISPLAY_HIGH_RESOLUTION MTK_BT_SUPPORT MTK_TABLET_DRAM MTK_FACEBEAUTY_SUPPORT EVDO_DT_VIA_SUPPORT MTK_FAN5405_SUPPORT MTK_BT_40_SUPPORT MTK_BT_PROFILE_FTP MTK_HIGH_QUALITY_THUMBNAIL MTK_FM_TX_SUPPORT MTK_BRAZIL_CUSTOMIZATION_VIVO MTK_BRAZIL_CUSTOMIZATION_CLARO HAVE_XLOG_FEATURE MTK_IPV6_SUPPORT MTK_AUTORAMA_SUPPORT MTK_EAP_SIM_AKA MTK_MATV_ANALOG_SUPPORT MTK_BASIC_PACKAGE MTK_BSP_PACKAGE MTK_BRAZIL_CUSTOMIZATION MTK_BT_PROFILE_A2DP MTK_BT_PROFILE_PRXR MTK_NVRAM_SECURITY CUSTOM_KERNEL_MAGNETOMETER MTK_BT_PROFILE_PAN MTK_CAMERA_APP_3DHW_SUPPORT MTK_WLAN_SUPPORT MTK_TETHERINGIPV6_SUPPORT MTK_AUTO_DETECT_ACCELEROMETER HAVE_CMMB_FEATURE MTK_MT8193_HDMI_SUPPORT MTK_EMMC_SUPPORT_OTP MTK_TB_APP_CALL_FORCE_SPEAKER_ON MTK_PRODUCT_INFO_SUPPORT MTK_FM_SHORT_ANTENNA_SUPPORT MTK_HDMI_SUPPORT MTK_BT_PROFILE_SPP MTK_BT_30_SUPPORT MTK_MT8193_NFI_SUPPORT MTK_ION_SUPPORT MTK_LCA_SUPPORT MTK_BT_PROFILE_DUN MTK_BT_PROFILE_PRXM MTK_FSCK_MSDOS_MTK MTK_MAV_SUPPORT HAVE_AWBENCODE_FEATURE MTK_BQ24196_SUPPORT MTK_CAMERA_BSP_SUPPORT MTK_FM_RX_SUPPORT MTK_WB_SPEECH_SUPPORT MTK_VT3G324M_SUPPORT ENCRY_PARTITION_SUPPORT MTK_SD_REINIT_SUPPORT MTK_SENSOR_SUPPORT MTK_EMMC_SUPPORT MTK_BT_21_SUPPORT MTK_BT_PROFILE_SIMAP MTK_COMBO_CORE_DUMP_SUPPORT MTK_DHCPV6C_WIFI MTK_EMULATOR_SUPPORT MTK_NAND_UBIFS_SUPPORT MTK_YAML_SCATTER_FILE_SUPPORT MTK_CTPPPOE_SUPPORT MTK_WORLD_PHONE MTK_THERMAL_PA_VIA_ATCMD MTK_SWIP_VORBIS MTK_PASSPOINT_R1_SUPPORT MTK_AUDIO_APE_SUPPORT MTK_AVI_PLAYBACK_SUPPORT USE_FRAUNHOFER_AAC MTK_DRM_APP MTK_OGM_PLAYBACK_SUPPORT MTK_MTKPS_PLAYBACK_SUPPORT MTK_BT_I2S_SUPPORT
AUTO_ADD_GLOBAL_DEFINE_BY_NAME_VALUE = MTK_CAM_ZSDHDR_SUPPORT MTK_CAM_ZSDMFB_SUPPORT MTK_AUDIO_MIC_INVERSE MTK_HAC_SUPPORT SIM_ME_LOCK_MODE MTK_CAM_CONTINUOUS_SHOT_MODE MTK_ICUSB_SUPPORT MTK_NFC_SE_NUM MTK_OVERLAY_ENGINE_SUPPORT MTK_COMBO_PSM_RX_TH MTK_COMBO_PSM_TX_TH MTK_PCB_BATTERY_SENSOR MTK_SIM1_SOCKET_TYPE MTK_SIM2_SOCKET_TYPE CUSTOM_KERNEL_MAIN2_IMGSENSOR CUSTOM_KERNEL_SSW MTK_LCM_PHYSICAL_ROTATION LCM_WIDTH MTK_SHARE_MODEM_SUPPORT MTK_SINGLE_3DSHOT_SUPPORT MTK_EXTERNAL_MODEM_SLOT MTK_NEON_SUPPORT MTK_SHARE_MODEM_CURRENT LCM_HEIGHT MTK_NTFS_OPENSOURCE_SUPPORT
AUTO_ADD_GLOBAL_DEFINE_BY_VALUE = CUSTOM_HAL_LENS BOOT_LOGO MTK_AUDIO_BLOUD_CUSTOMPARAMETER_REV MTK_PLATFORM CUSTOM_KERNEL_LENS CUSTOM_KERNEL_MAIN_BACKUP_LENS CUSTOM_KERNEL_LCM MTK_MODEM_SUPPORT MTK_ATV_CHIP CUSTOM_KERNEL_MAIN_IMGSENSOR MTK_BT_CHIP MTK_WLAN_CHIP CUSTOM_KERNEL_SUB_BACKUP_IMGSENSOR CUSTOM_KERNEL_MAIN_BACKUP_IMGSENSOR CUSTOM_KERNEL_FLASHLIGHT CUSTOM_KERNEL_SUB_IMGSENSOR CUSTOM_KERNEL_SUB_LENS CUSTOM_KERNEL_IMGSENSOR MTK_FM_RX_AUDIO MTK_COMBO_CHIP MTK_GPS_CHIP CUSTOM_KERNEL_SUB_BACKUP_LENS CUSTOM_KERNEL_MAIN_LENS MTK_FM_TX_AUDIO MTK_FM_CHIP CUSTOM_KERNEL_MAIN2_IMGSENSOR BOOT_LOGO
BOOT_LOGO = hd720
BUILD_CTS = yes
BUILD_KERNEL = yes
BUILD_LK = yes
BUILD_MTK_SDK =
BUILD_PRELOADER = yes
BUILD_UBOOT = no
CUSTOM_BUILD_VERNO =
# it is used to decide MT6620 combo chip BT and WiFi antenna architecture.  The meaning of each value is defined as follows. Please note that "CUSTOM_HAL_ANT" setting must be consistent with customer's MT6628 antenna architecture layout. Improper setting may lead to BT/WiFi malfunctions
CUSTOM_HAL_ANT = mt6628_ant_m1

# For audio flinger's customization folder
CUSTOM_HAL_AUDIOFLINGER = audio
CUSTOM_HAL_BLUETOOTH = bluetooth
CUSTOM_HAL_CAMERA = camera
CUSTOM_HAL_CAM_CAL = dummy_eeprom
# 1. This value is used to control MT6620 patch path 2. mt6620 should be used for when MTK_COMBO_CHIP is set to MT6620E3 or later version.
CUSTOM_HAL_COMBO = mt6628

# User space driver : Sensor module might have calibration data such as lens shading. You can adopt it according to EEPROM part number. Now, it's only s24cs64a_eeprom
CUSTOM_HAL_EEPROM = dummy_eeprom
# User space cameara flashlight driver.You can use this driver to choose cameara flashlight type.
CUSTOM_HAL_FLASHLIGHT = constant_flashlight

CUSTOM_HAL_IMGSENSOR = s5k4h5yx_mipi_raw ov8850_mipi_raw mt9m114_mipi_yuv
CUSTOM_HAL_LENS = fm50af sensordrive dummy_lens
CUSTOM_HAL_MAIN2_IMGSENSOR =
CUSTOM_HAL_MAIN_BACKUP_IMGSENSOR = 

# lens driver config for main camera (2nd solution)
CUSTOM_HAL_MAIN_BACKUP_LENS = sensordrive
# User space image sensor  driver: Main camera (rear camera) used sensor related tuning, setting and calibration information.Value is used main sensor name.
CUSTOM_HAL_MAIN_IMGSENSOR = s5k4h5yx_mipi_raw ov8850_mipi_raw

# lens driver config for main camera
CUSTOM_HAL_MAIN_LENS = fm50af
# M-sensor hal layer library including daemon
CUSTOM_HAL_MSENSORLIB = akmd8963 yamaha533

# sensor hal layer common part
CUSTOM_HAL_SENSORS = sensor
# User space image sensor driver: Sub camera (front camera )used backup sensor related tuning, setting and calibration information. Value is used sub backup sensor name.
CUSTOM_HAL_SUB_BACKUP_IMGSENSOR = 

# lens driver config for video telephony camera (2nd solution)
CUSTOM_HAL_SUB_BACKUP_LENS =
# User space driver: Sub camera (front camera )used sensor related tuning, setting and calibration information. Value is used sub sensor name.
CUSTOM_HAL_SUB_IMGSENSOR = mt9m114_mipi_yuv

# lens driver config for video telephony camera
CUSTOM_HAL_SUB_LENS = dummy_lens
# accelerometer sensor to detect accelerometer from x y z axis.
CUSTOM_KERNEL_ACCELEROMETER = lis3dh_auto mma8452q_auto

# ALSPS sensor driverto detect ambint light and the object is close or far awary from device
CUSTOM_KERNEL_ALSPS = tmd2771_HW

# The battery feature is the MUST include feature and can not be disable.This feature provides battery monitor and charging. The system can not boot up without battery.
CUSTOM_KERNEL_BATTERY = battery
CUSTOM_KERNEL_CAMERA = camera
CUSTOM_KERNEL_CAM_CAL = dummy_eeprom
CUSTOM_KERNEL_CORE = src
CUSTOM_KERNEL_DCT = dct
CUSTOM_KERNEL_EEPROM = dummy_eeprom
CUSTOM_KERNEL_FLASHLIGHT = constant_flashlight
CUSTOM_KERNEL_GYROSCOPE = mpu3000
CUSTOM_KERNEL_HEADSET = accdet
# Kernel space image sensor driver. Define  project used all image sensors .The value is combination of CUSTOM_KERNEL_MAIN_IMGSENSOR, CUSTOM_KERNEL_MAIN_BACKUP_IMGSENSOR, CUSTOM_KERNEL_SUB_IMGSENSOR, and CUSTOM_KERNEL_SUB_BACKUP_IMGSENSOR
CUSTOM_KERNEL_IMGSENSOR = s5k4h5yx_mipi_raw ov8850_mipi_raw mt9m114_mipi_yuv
# key pad driver to report key event
CUSTOM_KERNEL_KPD = kpd
# To choose kernel LCM driver name
CUSTOM_KERNEL_LCM = otm1282a_hd720_dsi_cmd

# leds driver including green/red/blue
CUSTOM_KERNEL_LEDS = mt65xx
CUSTOM_KERNEL_LENS = fm50af sensordrive dummy_lens
CUSTOM_KERNEL_MAGNETOMETER = akm8963_auto yamaha533_auto

# compass driver to detect compass raw data and report orientatino data
CUSTOM_KERNEL_MAIN2_BACKUP_IMGSENSOR = 
CUSTOM_KERNEL_MAIN2_IMGSENSOR =
CUSTOM_KERNEL_MAIN_BACKUP_IMGSENSOR =
#ov12830_mipi_raw

# lens driver config for main camera (2nd solution)
CUSTOM_KERNEL_MAIN_BACKUP_LENS = dummy_lens

# Kernel space image sensor driver:Main camera (rear camera) used sensor driver.Value is used main sensor name.
CUSTOM_KERNEL_MAIN_IMGSENSOR = s5k4h5yx_mipi_raw ov8850_mipi_raw

# lens driver config for main camera
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_RTC = rtc
# For audio kernel driver's speaker customization folder definition.
CUSTOM_KERNEL_SOUND = amp_6320pmic_spk
CUSTOM_KERNEL_SSW = ssw_generic

# Kernel space image sensor driver:Sub camera (front camera) used backup sensor driver.Value is used sub backup sensor name.
CUSTOM_KERNEL_SUB_BACKUP_IMGSENSOR = 

# lens driver config for video telephony camera (2nd solution)
CUSTOM_KERNEL_SUB_BACKUP_LENS =
# Kernel space image sensor driver:Sub camera (front camera) used sensor driver.Value is used sub sensor name.
CUSTOM_KERNEL_SUB_IMGSENSOR = mt9m114_mipi_yuv

# lens driver config for video telephony camera
CUSTOM_KERNEL_SUB_LENS = dummy_lens
# touch driver  need to report correct touch axes
CUSTOM_KERNEL_TOUCHPANEL = cyttsp4

# Configuration for USB PHY
CUSTOM_KERNEL_USB = mt6577
CUSTOM_KERNEL_VIBRATOR = vibrator
# To choose LK LCM driver name
CUSTOM_LK_LCM = otm1282a_hd720_dsi_cmd

# Define which modem will be used.
CUSTOM_MODEM = huawei89_we_kk_md1_hspa

# Support customer to implement and apply their own RSA security functions
CUSTOM_SEC_AUTH_SUPPORT = no
CUSTOM_SEC_SIGNTOOL_SUPPORT = no
CUSTOM_UBOOT_LCM = otm1282a_hd720_dsi_cmd
DISABLE_EARPIECE = no
ENCRY_PARTITION_SUPPORT = no
EVB = no
EVDO_DT_SUPPORT = no
EVDO_DT_VIA_SUPPORT = no
EVDO_IR_SUPPORT = no
FEATURE_FTM_AUDIO_AUTOTEST = yes
FEATURE_FTM_AUDIO_TEST = yes
GEMINI = yes
GOOGLE_RELEASE_RIL = no
HAVE_AACENCODE_FEATURE = yes
HAVE_ADPCMENCODE_FEATURE = yes
HAVE_AEE_FEATURE = yes
HAVE_AWBENCODE_FEATURE = yes
HAVE_CMMB_FEATURE = no
HAVE_MATV_FEATURE = no
HAVE_SRSAUDIOEFFECT_FEATURE = no
HAVE_VORBISENC_FEATURE = yes
HAVE_XLOG_FEATURE = yes
HW_HAVE_TP_THREAD = no
IS_VCORE_USE_6333VCORE = no
IS_VM_USE_6333VM = no
IS_VRF18_USE_6333VRF18 = no
KBUILD_OUTPUT_SUPPORT = yes
LCM_HEIGHT = 1280
LCM_WIDTH = 720
LINUX_KERNEL_VERSION = kernel-3.10
MALLOC_IMPL = jemalloc
MD5_SIZE = 0x01600000
MD5_SMEM_SIZE = 0x00200000
MTK_2IN1_SPK_SUPPORT = no
MTK_2SDCARD_SWAP = no
MTK_3GDONGLE_SUPPORT = no
MTK_75DISPLAY_ENHANCEMENT_SUPPORT = no
MTK_AAL_SUPPORT = no
MTK_ACMT_DEBUG = no
MTK_AGPS_APP = yes
MTK_AIV_SUPPORT = no
MTK_ANDROIDFACTORYMODE_APP = yes
MTK_ANTIBRICKING_LEVEL = 2
MTK_API_CHECK = yes
MTK_APP_GUIDE = yes
MTK_AP_SPEECH_ENHANCEMENT = no
MTK_ASD_SUPPORT = yes
MTK_ASR_SUPPORT = no
MTK_ATV_CHIP =
MTK_AUDENH_SUPPORT = yes
MTK_AUDIO = yes
MTK_AUDIO_ADPCM_SUPPORT = yes
MTK_AUDIO_ALAC_SUPPORT = yes
MTK_AUDIO_APE_SUPPORT = yes
MTK_AUDIO_BLOUD_CUSTOMPARAMETER_REV = MTK_AUDIO_BLOUD_CUSTOMPARAMETER_V4
MTK_AUDIO_CHANGE_SUPPORT = no
MTK_AUDIO_DDPLUS_SUPPORT = no
MTK_AUDIO_EXTCODEC_SUPPORT = no
MTK_AUDIO_HD_REC_SUPPORT = yes
MTK_AUDIO_MIC_INVERSE = no
MTK_AUDIO_PROFILES = yes
MTK_AUDIO_RAW_SUPPORT = yes
MTK_AUIDO_MIC_INVERSE = no
MTK_AUTOIP_SUPPORT = no
MTK_AUTORAMA_SUPPORT = yes
# one load to support different accelerometer sensor
MTK_AUTO_DETECT_ACCELEROMETER = yes

# one load to support different magnetometer sensor
MTK_AUTO_DETECT_MAGNETOMETER = yes
MTK_AUTO_DETECT_ALSPS = no
MTK_AUTO_SANITY = yes
MTK_AVI_PLAYBACK_SUPPORT = yes
MTK_BASIC_PACKAGE = no
MTK_BATLOWV_NO_PANEL_ON_EARLY = no
MTK_BEAM_PLUS_SUPPORT = yes
MTK_BESLOUDNESS_SUPPORT = yes
MTK_BESSURROUND_SUPPORT = no
MTK_BG_POWER_SAVING_SUPPORT = yes
MTK_BG_POWER_SAVING_UI_SUPPORT = yes
MTK_BICR_SUPPORT = yes
MTK_BIP_SCWS = yes
MTK_BQ24156_SUPPORT = no
MTK_BQ24158_SUPPORT = no
MTK_BQ24297_SUPPORT = no
MTK_BQ27541_SUPPORT = no
MTK_BRANCH = L1.MP12
MTK_BRAZIL_CUSTOMIZATION = no
MTK_BRAZIL_CUSTOMIZATION_CLARO = no
MTK_BRAZIL_CUSTOMIZATION_TIM = no
MTK_BRAZIL_CUSTOMIZATION_VIVO = no
MTK_BSP_PACKAGE = no
MTK_BT_21_SUPPORT = yes
MTK_BT_30_HS_SUPPORT = no
MTK_BT_30_SUPPORT = yes
MTK_BT_40_LE_STANDALONE = no
MTK_BT_40_SUPPORT = yes
MTK_BT_BLE_MANAGER_SUPPORT = yes
MTK_BT_CHIP = MTK_MT6628
MTK_BT_FM_OVER_BT_VIA_CONTROLLER = no
MTK_BT_I2S_SUPPORT = no
MTK_BT_POWER_EFFICIENCY_ENHANCEMENT = yes
MTK_BT_PROFILE_A2DP = no
MTK_BT_PROFILE_AVRCP = no
MTK_BT_PROFILE_AVRCP13 = no
MTK_BT_PROFILE_AVRCP14 = no
MTK_BT_PROFILE_BIP = yes
MTK_BT_PROFILE_BPP = yes
MTK_BT_PROFILE_DUN = yes
MTK_BT_PROFILE_FTP = yes
MTK_BT_PROFILE_HFP = no
MTK_BT_PROFILE_HIDH = no
MTK_BT_PROFILE_MANAGER = yes
MTK_BT_PROFILE_MAPC = yes
MTK_BT_PROFILE_MAPS = yes
MTK_BT_PROFILE_OPP = no
MTK_BT_PROFILE_PAN = no
MTK_BT_PROFILE_PBAP = no
MTK_BT_PROFILE_PRXM = yes
MTK_BT_PROFILE_PRXR = yes
MTK_BT_PROFILE_SIMAP = yes
MTK_BT_PROFILE_SPP = no
MTK_BT_PROFILE_TIMEC = no
MTK_BT_PROFILE_TIMES = no
MTK_BT_SUPPORT = yes
MTK_BUFFER_COMPRESSION_SUPPORT = no
MTK_BUILD_VERNO = ALPS.L1.MP12.V1.2_WT6589.WE.L1
MTK_BWC_SUPPORT = yes
MTK_CACHE_MERGE_SUPPORT = no
MTK_CALENDAR_IMPORTER_APP = yes
MTK_CAMCORDER_PROFILE_MID_MP4 = no
MTK_CAMERA_APP = no
MTK_CAMERA_APP_3DHW_SUPPORT = yes
MTK_CAMERA_BSP_SUPPORT = yes
MTK_CAMERA_OT_SUPPORT = no
MTK_CAM_ASD_SUPPORT = yes
MTK_CAM_CONTINUOUS_SHOT_MODE = 1
MTK_CAM_DEPTH_AF_SUPPORT = no
MTK_CAM_FACEBEAUTY_SUPPORT = yes
MTK_CAM_FD_SUPPORT = yes
MTK_CAM_GESTURE_SUPPORT = no
MTK_CAM_HDR_SUPPORT = yes
MTK_CAM_IMAGE_REFOCUS_SUPPORT = NONE
MTK_CAM_MAV_SUPPORT = yes
MTK_CAM_NATIVE_PIP_SUPPORT = no
MTK_CAM_NR3D_SUPPORT = no
MTK_CAM_OT_SUPPORT = no
MTK_CAM_SD_SUPPORT = yes
MTK_CAM_STEREO_CAMERA_SUPPORT = no
MTK_CAM_VHDR_SUPPORT = no
MTK_CAM_VIDEO_FACEBEAUTY_SUPPORT = no
MTK_CAM_VSS_SUPPORT = yes
MTK_CAM_ZSDHDR_SUPPORT = no
MTK_CAM_ZSDMFB_SUPPORT = no
MTK_CAM_ZSD_SUPPORT = yes
MTK_CC33_SUPPORT = no
MTK_CDS_EM_SUPPORT = yes
MTK_CELL_BROADCAST_RECEIVER_SUPPORT = no
MTK_CHIPTEST_INT = no
MTK_CHIP_VER = S01
MTK_CHKIMGSIZE_SUPPORT = no
MTK_CIP_SUPPORT = no
MTK_CLEARMOTION_SUPPORT = no
MTK_CMAS_SUPPORT = no
MTK_CMCC_FT_PRECHECK_SUPPORT = no
MTK_COMBO_CHIP = MT6628
# valid_value_list = yes,no
MTK_COMBO_CORE_DUMP_SUPPORT = yes
MTK_COMBO_NAND_SUPPORT = no
MTK_COMBO_PSM_RX_TH = 1600
MTK_COMBO_PSM_TX_TH = 400
MTK_COMBO_QUICK_SLEEP_SUPPORT = yes

# used to describe whether WCN combo chip(MT6628/MT6628/MT6629,etc.) is supported or not
MTK_COMBO_SUPPORT = yes
MTK_CSD_DIALER_SUPPORT = no
# target type cpu
MTK_CPU = arm_cortexa7

# CTA case request, Only China Operator & OM project need support. WW project don't need support.
MTK_CTA_SET = yes
MTK_CTA_SUPPORT = no
MTK_CTPPPOE_SUPPORT = no
MTK_CTP_RESET_CONFIG = no
MTK_CTSC_MTBF_INTERNAL_SUPPORT = no
MTK_CUSTOMERSERVICE_APP = no
MTK_CUSTOM_720P = no
MTK_DAL_SUPPORT = no
MTK_DATA_TRANSFER_APP = yes
MTK_DEDICATEDAPN_SUPPORT = no
MTK_DEFAULT_DATA_OFF = no
MTK_DEINTERLACE_SUPPORT = no
MTK_DENA_MINIROSANGUO_APP = no
MTK_DENA_MOBAGE_APP = no
MTK_DEVREG_APP = no
MTK_DFO_RESOLUTION_SUPPORT = no
MTK_DHCPV6C_WIFI = yes
MTK_DIALER_SEARCH_SUPPORT = yes
MTK_DIGITAL_MIC_SUPPORT = no
MTK_DISABLE_CAPABILITY_SWITCH = no
MTK_DISABLE_EFUSE = no
MTK_DISABLE_POWER_ON_OFF_VOLTAGE_LIMITATION = no
MTK_DISPLAY_HIGH_RESOLUTION = no
MTK_DITHERING_SUPPORT = yes
# Define DMNR tuning recording source.
MTK_DMNR_TUNING_AT_MD=yes
MTK_DM_AGENT_SUPPORT=yes

# Device Management. For example, collection or configuration parameter's of device, upgrade software, lock or unlock device, wipe data, etc.
MTK_DM_APP = no
MTK_DM_ENTRY_DISPLAY = no
MTK_DM_RELEASE = no
MTK_DOLBY_DAP_SUPPORT = no
MTK_DP_FRAMEWORK = yes
MTK_DRM_APP = yes
MTK_DRM_KEY_MNG_SUPPORT = no
MTK_DRM_PLAYREADY_SUPPORT = no
MTK_DTAG_DUAL_APN_SUPPORT = no
MTK_DT_SUPPORT = no
MTK_DUAL_INPUT_CHARGER_SUPPORT = no
MTK_DUAL_MIC_SUPPORT = yes
MTK_DVFS_DISABLE_LOW_VOLTAGE_SUPPORT = no
MTK_DX_HDCP_SUPPORT = no
MTK_EAP_SIM_AKA = yes
MTK_EFUSE_WRITER_SUPPORT = no
MTK_EMMC_DISCARD = no
MTK_EMMC_SUPPORT = yes
MTK_EMMC_SUPPORT_OTP = no
MTK_EMULATOR_SUPPORT = no
MTK_ENABLE_DIVX_DECODER = no
MTK_ENABLE_MD1 = yes
MTK_ENABLE_MD2 = no
MTK_ENABLE_MD5 = no
MTK_ENABLE_S263_DECODER = no
MTK_ENABLE_VIDEO_EDITOR = no
MTK_ENGINEERMODE_APP = yes
MTK_EPDG_SUPPORT = no
MTK_ETWS_SUPPORT = no
MTK_EXLOG2MAIL_APP = no
MTK_FACEBEAUTY_SUPPORT = yes
MTK_FACTORY_MODE_IN_GB2312 = yes
MTK_FACTORY_RESET_PROTECTION_SUPPORT = yes
MTK_FAN5402_SUPPORT = no
# use external charger IC, MTK support
MTK_FAN5405_SUPPORT = no
MTK_FASTBOOT_SUPPORT = no
MTK_FAT_ON_NAND = no
MTK_FD_FORCE_REL_SUPPORT = yes
MTK_FD_SUPPORT = yes
MTK_FEMTO_CELL_SUPPORT = no
# Support Fast Dormancy or not
MTK_FD_SUPPORT = yes

MTK_FENCE_SUPPORT = yes

# use this feature option to enable/disable File Manager App
MTK_FILEMANAGER_APP = yes
MTK_FIRST_MD = 1
MTK_FLIGHT_MODE_POWER_OFF_MD = yes
MTK_FLV_PLAYBACK_SUPPORT = yes
MTK_FMRADIO_APP = yes
MTK_FM_50KHZ_SUPPORT = no
# Used in FM driver and Native lib makefiles to decide which chip driver will be build
MTK_FM_CHIP = MT6628_FM

# For FM record function enable option.
MTK_FM_RECORDING_SUPPORT = yes
# define FM TX type digital or analog
MTK_FM_RX_AUDIO = FM_ANALOG_INPUT

# support FM RX or not
MTK_FM_RX_SUPPORT = yes
MTK_FM_SHORT_ANTENNA_SUPPORT = no
MTK_FM_SUPPORT = yes
# define FM TX type digital or analog
MTK_FM_TX_AUDIO = FM_ANALOG_OUTPUT

#   if "yes", FM TX feature will be built in system.
MTK_FM_TX_SUPPORT = no
MTK_FOTA_ENTRY = no
MTK_FOTA_RELEASE = no
MTK_FOTA_SUPPORT = no
MTK_FSCK_MSDOS_MTK = no
MTK_FSCK_TUNE = no
MTK_FW_UPGRADE = yes
MTK_FW_UPGRADE_APP = no
MTK_GALLERY_VIDEOPLAYER_APP = no
MTK_GAMELOFT_ASPHALTINJECTION_APP = no
MTK_GAMELOFT_GLLIVE_APP = no
MTK_GAMELOFT_KINGDOMANDLORDS_CN_APP = no
MTK_GAMELOFT_KINGDOMANDLORDS_WW_APP = no
MTK_GAMELOFT_UNOANDFRIENDS_CN_APP = no
MTK_GAMELOFT_UNOANDFRIENDS_WW_APP = no
MTK_GAMELOFT_WONDERZOO_CN_APP = no
MTK_GAMELOFT_WONDERZOO_WW_APP = no
MTK_GEMINI_3SIM_SUPPORT = no
MTK_GEMINI_4SIM_SUPPORT = no
# Enable or disable the 3G Switch feature
MTK_GEMINI_3G_SWITCH = yes

# Enable or disable the GEMINI enhancement
MTK_GEMINI_ENHANCEMENT = yes
MTK_GEMINI_SMART_3G_SWITCH = 1
MTK_GOOGLEOTA_SUPPORT = no
MTK_GPS_CHIP = MTK_GPS_MT6628
MTK_GPS_SUPPORT = yes
MTK_GPT_SCHEME_SUPPORT = no
MTK_GPU_CHIP = SGX544_115
MTK_GPU_SUPPORT = yes
MTK_HAC_SUPPORT = no
MTK_HANDSFREE_DMNR_SUPPORT = yes
MTK_HDMI_HDCP_SUPPORT = no
MTK_HDMI_SUPPORT = no
MTK_HEADER_SUPPORT = yes
MTK_HEART_RATE_MONITOR_SUPPORT = no
MTK_HETCOMM_SUPPORT = no
MTK_HIGH_QUALITY_THUMBNAIL = yes
MTK_HIGH_RESOLUTION_AUDIO_SUPPORT = no
MTK_HOTKNOT_SUPPORT = yes
MTK_HUIYOU_SYJT_APP = no
MTK_HUIYOU_WABAOJINGYING_APP = no
# Used to enable hwcomposer
MTK_HWC_SUPPORT = yes
MTK_HWC_VERSION = 1.2
MTK_HWUI_SUPPORT = yes
MTK_HW_ENHANCE = no
MTK_HW_KEY_REMAPPING = no
MTK_ICUSB_SUPPORT = no
MTK_IME_ARABIC_SUPPORT = no
MTK_IME_FRENCH_SUPPORT = no
MTK_IME_GERMAN_SUPPORT = no
MTK_IME_HANDWRITING_ENGINE = none
MTK_IME_HINDI_SUPPORT = no
MTK_IME_INDONESIAN_SUPPORT = no
MTK_IME_INPUT_ENGINE = none
MTK_IME_ITALIAN_SUPPORT = no
MTK_IME_MALAY_SUPPORT = no
MTK_IME_PORTUGUESE_SUPPORT = no
MTK_IME_RUSSIAN_SUPPORT = no
MTK_IME_SPANISH_SUPPORT = no
MTK_IME_SUPPORT = no
MTK_IME_THAI_SUPPORT = no
MTK_IME_TURKISH_SUPPORT = no
MTK_IME_VIETNAM_SUPPORT = no
MTK_INCALL_HANDSFREE_DMNR = no
MTK_INCALL_NORMAL_DMNR = no
MTK_INCLUDE_MODEM_DB_IN_IMAGE = yes
MTK_INPUTMETHOD_COOTEKIME_TOUCHPAL = yes
MTK_INTERNAL = no
MTK_INTERNAL_API_CHECK = no
MTK_INTERNAL_HDMI_SUPPORT = no
MTK_INTERNAL_LANG_SET = no
MTK_INTERNAL_MHL_SUPPORT = no
MTK_IN_HOUSE_TEE_SUPPORT = no
MTK_ION_SUPPORT = yes
MTK_IPOH_SUPPORT = yes
MTK_IPO_SUPPORT = yes
MTK_IPV6_SUPPORT = yes
MTK_IPV6_TETHER_NDP_MODE = no
MTK_IPV6_TETHER_PD_MODE = no
MTK_ISMS_SUPPORT = no
MTK_JEITA_STANDARD_SUPPORT = no
MTK_KERNEL_POWER_OFF_CHARGING = yes
MTK_LAUNCHER_UNREAD_SUPPORT = yes
MTK_LCEEFT_SUPPORT = yes
MTK_LCM_PHYSICAL_ROTATION = 0
MTK_LIVEWALLPAPER_APP = yes
MTK_LIVE_PHOTO_SUPPORT = yes
MTK_LOCKSCREEN_TYPE = 1
MTK_LOG2SERVER_APP = no
MTK_LOG2SERVER_INTERNAL = no
MTK_LOSSLESS_BT_SUPPORT = no
MTK_LOW_BAND_TRAN_ANIM = no
MTK_LTE_DC_SUPPORT = no
MTK_LTE_SUPPORT = no
MTK_M4U_SUPPORT = yes
MTK_MASS_STORAGE = yes
MTK_MATV_ANALOG_SUPPORT = yes
MTK_MATV_SERIAL_IF_SUPPORT = no
MTK_MAV_PLAYBACK_SUPPORT = yes
MTK_MAV_SUPPORT = no
# modem 1 mode.
MTK_MD1_SUPPORT = 2
MTK_MD2_SUPPORT = 2
MTK_MD5_SUPPORT = 5
MTK_MDLOGGER_SUPPORT = yes
MTK_MDM_APP = no
MTK_MDM_FUMO = no
MTK_MDM_LAWMO = no
MTK_MDM_SCOMO = no
MTK_MD_SHUT_DOWN_NT = yes
MTK_MEMORY_COMPRESSION_SUPPORT = no
MTK_MFV_MPEG4_EXTRA = no
MTK_MLC_NAND_SUPPORT = no
MTK_MMPROFILE_SUPPORT = no
MTK_MMUMAP_SUPPORT = no
MTK_MOBILE_MANAGEMENT = yes
MTK_MODEM_SUPPORT =
MTK_MOTION_TRACK_SUPPORT = yes
MTK_MSDC1_NOT_SUPPORT_SDR104 = no
MTK_MT519X_FM_SUPPORT = no
MTK_MT6333_SUPPORT = no
MTK_MT8193_HDCP_SUPPORT = no
MTK_MT8193_HDMI_SUPPORT = no
MTK_MT8193_NFI_SUPPORT = no
MTK_MT8193_SUPPORT = no
MTK_MTKLOGGER_SUPPORT = yes
MTK_MTKPS_PLAYBACK_SUPPORT = no
MTK_MULTIBRIDGE_SUPPORT = no
MTK_MULTICORE_OBSERVER_APP = yes
MTK_MULTISIM_RINGTONE_SUPPORT = no
MTK_MULTI_PARTITION_MOUNT_ONLY_SUPPORT = no
MTK_MULTI_STORAGE_SUPPORT = yes
MTK_MUSIC_LRC_SUPPORT = no
MTK_NAND_PAGE_SIZE = 2K
MTK_NAND_UBIFS_SUPPORT = no
MTK_NATIVE_FENCE_SUPPORT = no

# Control NEON HW support or not
MTK_NEON_SUPPORT = yes
MTK_NETWORK_TYPE_ALWAYS_ON = no
MTK_NETWORK_TYPE_DISPLAY = no
MTK_NEW_COMBO_EMMC_SUPPORT = no
MTK_NEW_IPTABLES_SUPPORT = yes
MTK_NFC_ADDON_SUPPORT = no
MTK_NFC_APP_SUPPORT = no
MTK_NFC_FW_MT6605 = no
MTK_NFC_HCE_SUPPORT = no
MTK_NFC_MT6605 = yes
MTK_NFC_OMAAC_CMCC = no
MTK_NFC_OMAAC_GEMALTO = no
MTK_NFC_OMAAC_SUPPORT = no
MTK_NFC_SE_NUM = 7
MTK_NFC_SUPPORT = no
MTK_NOTEBOOK_SUPPORT = no
MTK_NO_NEED_USB_LED = no
MTK_NO_TRAN_ANIM = no
MTK_NTFS_OPENSOURCE_SUPPORT = yes
MTK_NVRAM_SECURITY = no
MTK_OGM_PLAYBACK_SUPPORT = no
MTK_OMACP_SUPPORT = yes
MTK_OMADRM_SUPPORT = yes
MTK_OMA_DOWNLOAD_SUPPORT = yes
MTK_ONLY_OWNER_SIM_SUPPORT = no
MTK_OOBE_APP = no
MTK_OVERLAY_ENGINE_SUPPORT = no
MTK_OWNER_SDCARD_ONLY_SUPPORT = no
MTK_PARTITION_TABLE_PLAIN_TEXT = no
MTK_PASSPOINT_R1_SUPPORT = no
MTK_PASSPOINT_R2_SUPPORT = no
MTK_PCB_BATTERY_SENSOR = no
MTK_PERFSERVICE_SUPPORT = yes
MTK_PERMISSION_CONTROL = yes
MTK_PERSIST_PARTITION_SUPPORT = no
MTK_PHONE_NUMBER_GEODESCRIPTION = yes
MTK_PHONE_VOICE_RECORDING = yes
MTK_PHONE_VT_VOICE_ANSWER = no
MTK_PLATFORM = MT6589
MTK_PLATFORM_OPTIMIZE = yes
MTK_PLAYREADY_SUPPORT = no
MTK_PM_STATS_SUPPORT = no
MTK_POWER_EXT_DETECT = no
MTK_PQ_SUPPORT = PQ_HW_VER_2
MTK_PRIVACY_PROTECTION_LOCK = no
MTK_PRODUCT_INFO_SUPPORT = yes
MTK_PRODUCT_LOCALES = en_US zh_CN zh_TW es_ES pt_BR ru_RU fr_FR de_DE tr_TR vi_VN ms_MY in_ID th_TH it_IT ar_EG hi_IN bn_IN ur_PK fa_IR pt_PT nl_NL el_GR hu_HU tl_PH ro_RO cs_CZ ko_KR km_KH iw_IL my_MM pl_PL es_US bg_BG hr_HR lv_LV lt_LT sk_SK uk_UA de_AT da_DK fi_FI nb_NO sv_SE en_GB hy_AM zh_HK et_EE ja_JP kk_KZ sr_RS sl_SI ca_ES
MTK_RADIOOFF_POWER_OFF_MD = no
MTK_RAT_WCDMA_PREFERRED = yes
MTK_RCSE_SUPPORT = no
MTK_RCS_SUPPORT = no
MTK_REGIONALPHONE_SUPPORT = no
MTK_RELEASE_PACKAGE = rel_customer_basic rel_customer_platform_mt6589
MTK_RILD_READ_IMSI = no
MTK_ROTATION_OFFSET_SUPPORT = no
MTK_RSDM_APP = no
MTK_RTP_OVER_RTSP_SUPPORT = yes
MTK_RTSP_BITRATE_ADAPTATION_SUPPORT = no
MTK_SAFEMEDIA_SUPPORT = no
MTK_SCOMO_ENTRY = no
MTK_SCREEN_OFF_WIFI_OFF = no
MTK_SDIOAUTOK_SUPPORT = no
MTK_SD_REINIT_SUPPORT = no
MTK_SD_SUPPORT = yes
MTK_SEARCH_DB_SUPPORT = yes
MTK_SECURITY_SW_SUPPORT = yes
MTK_SEC_BOOT = ATTR_SBOOT_ONLY_ENABLE_ON_SCHIP
MTK_SEC_CHIP_SUPPORT = yes
MTK_SEC_MODEM_AUTH = no
MTK_SEC_MODEM_ENCODE = no
MTK_SEC_MODEM_NVRAM_ANTI_CLONE = no
MTK_SEC_SECRO_AC_SUPPORT = yes
MTK_SEC_USBDL = ATTR_SUSBDL_ONLY_ENABLE_ON_SCHIP
MTK_SEC_VIDEO_PATH_SUPPORT = no
MTK_SEC_WFD_VIDEO_PATH_SUPPORT = no
MTK_SEND_RR_SUPPORT = yes
MTK_SENSOR_SUPPORT = yes
MTK_SHARED_SDCARD = yes
MTK_SHARE_MODEM_CURRENT = 2
MTK_SHARE_MODEM_SUPPORT = 2
MTK_SIGNATURE_CUSTOMIZATION = no
MTK_SIGNMODEM_SUPPORT = yes
MTK_SIM1_SOCKET_TYPE = 1
MTK_SIM2_SOCKET_TYPE = 1
MTK_SIM_AUTHENTICATION_SUPPORT = no
MTK_SIM_HOT_SWAP = yes
MTK_SIM_HOT_SWAP_COMMON_SLOT = no
MTK_SIM_RECOVERY = yes
MTK_SINA_WEIBO_SUPPORT = no
MTK_SINGLE_3DSHOT_SUPPORT = no
MTK_SINGLE_IMEI = no
MTK_SIP_SUPPORT = no
MTK_SLIDEVIDEO_SUPPORT = no
MTK_SLOW_MOTION_VIDEO_SUPPORT = no
MTK_SMARTBOOK_SUPPORT = no
MTK_SMSREG_APP = no
MTK_SMS_FILTER_SUPPORT = yes
MTK_SMT_SUPPORT = no
MTK_SPEAKER_MONITOR_SUPPORT = no
MTK_SPECIAL_FACTORY_RESET = no
MTK_SPECIFIC_SM_CAUSE = no
MTK_SUBTITLE_SUPPORT = no
MTK_SUPPORT_MJPEG = no
MTK_SUPPORT_TC1_TUNNING = no
MTK_SWCHR_SUPPORT = no
MTK_SWIP_VORBIS = yes
MTK_SWIP_WMAPRO = no
MTK_SYSTEM_UPDATE_SUPPORT = yes
MTK_TABLET_PLATFORM = no
MTK_TABLET_PLUGIN_BUILD = no
MTK_TB_APP_CALL_FORCE_SPEAKER_ON = no
MTK_TB_APP_LANDSCAPE_SUPPORT = no
MTK_TC1_FEATURE = no
MTK_TELEPHONY_BOOTUP_MODE_SLOT1 = 0
MTK_TELEPHONY_BOOTUP_MODE_SLOT2 = 1
MTK_TELEPHONY_MODE = 1
MTK_TER_SERVICE = no
MTK_TETHERINGIPV6_SUPPORT = yes
MTK_TETHERING_EEM_SUPPORT = no
MTK_THERMAL_PA_VIA_ATCMD = no
MTK_TINY_UTIL = yes
MTK_TRANSPARENT_BAR_SUPPORT = no
MTK_TTY_SUPPORT = yes
MTK_TVOUT_SUPPORT = no
MTK_UART_USB_SWITCH = no
MTK_ULTRA_DIMMING_SUPPORT = no
MTK_UMTS_TDD128_MODE = no
MTK_USB_AUDIO_SUPPORT = yes
MTK_USER_ROOT_SWITCH = no
MTK_USER_SPACE_DEBUG_FW = yes
MTK_USES_HD_VIDEO = yes
MTK_USES_VR_DYNAMIC_QUALITY_MECHANISM = yes
MTK_USE_ANDROID_MM_DEFAULT_CODE = no
MTK_USE_RESERVED_EXT_MEM = no
MTK_VIBSPK_SUPPORT = no
MTK_VIDEO_1080P = no
MTK_VIDEO_FAVORITES_WIDGET_APP = no
MTK_VIDEO_HEVC_SUPPORT = no
MTK_VIDEO_THUMBNAIL_PLAY_SUPPORT = yes
MTK_VLW_APP = yes
MTK_VOICE_CONTACT_SEARCH_SUPPORT = no
MTK_VOICE_INTERFACE_EXTENSION_SUPPORT = yes
MTK_VOICE_UI_SUPPORT = yes
MTK_VOICE_UNLOCK_SUPPORT = yes
MTK_VOIP_ENHANCEMENT_SUPPORT = no
MTK_VOIP_HANDSFREE_DMNR = no
MTK_VOIP_NORMAL_DMNR = no
MTK_VOW_SUPPORT = no
MTK_VT3G324M_SUPPORT = yes
MTK_WAPI_SUPPORT = yes
MTK_WAPPUSH_SUPPORT = yes
MTK_WB_SPEECH_SUPPORT = yes
MTK_WEATHER_PROVIDER_APP = yes
MTK_WEATHER_WIDGET_APP = yes
MTK_WEB_NOTIFICATION_SUPPORT = yes
MTK_WEEK_NO = W16.20
MTK_WFD_HDCP_TX_SUPPORT = no
MTK_WFD_SINK_SUPPORT = yes
MTK_WFD_SINK_UIBC_SUPPORT = yes
MTK_WFD_SUPPORT = yes
MTK_WIFIWPSP2P_NFC_SUPPORT = no
MTK_WIFI_CALLING_RIL_SUPPORT = no
MTK_WIFI_MCC_SUPPORT = yes
MTK_WIFI_P2P_SUPPORT = yes
MTK_WLAN_CHIP = MT6628
MTK_WLAN_SUPPORT = yes
MTK_WMA_PLAYBACK_SUPPORT = yes
MTK_WML_SUPPORT = yes
MTK_WMV_PLAYBACK_SUPPORT = yes
MTK_WORLD_PHONE = no
MTK_WVDRM_L1_SUPPORT = no
MTK_WVDRM_SUPPORT = yes
MTK_YAML_SCATTER_FILE_SUPPORT = no
MULTI_CH_PLAYBACK_SUPPORT = no
NAND_OTP_SUPPORT = no
NO_INIT_PERMISSION_CHECK = yes
NXP_SMARTPA_SUPPORT = no
OP01_COMPATIBLE = no
OP01_CTS_COMPATIBLE_DFOSET = no
OPTR_SPEC_SEG_DEF = NONE
PURE_AP_USE_EXTERNAL_MODEM = no
SIM_ME_LOCK_MODE = 0
SIM_REFRESH_RESET_BY_MODEM = no
TARGET_ARCH_VARIANT = armv7-a-neon
TARGET_USES_LOGD = false
TRUSTONIC_TEE_SUPPORT = no
USE_FRAUNHOFER_AAC = yes
WIFI_WEP_KEY_ID_SET = no
MTK_TEE_SUPPORT = no

#CREATE_PROJECT_INFO=2016051295710
