LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := FMRadio
LOCAL_SRC_FILES := FMRadio.apk
LOCAL_MODULE_TAGS := optional
LOCAL_JNI_SHARED_LIBRARIES := libfmjni
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false 
include $(BUILD_PREBUILT)
